swagger: "2.0"
info:
  description: |-
    RTCA is a customer address verification service. it get customer id as input and verify the address.Respond  whether the customer is valid or not
  version: "1.0.0"
  title: "REAL TIME CUSTOMER ADDRESS CHECK"

host: localhost:8080
basePath: /

schemes:
  - "https"
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /customerAddressEligibility:
    post:
      tags:
        - "customerAddressEligibility"
      summary: "Verify the Customer address"
      description: "Check the Customer address"
      operationId: "postCustomerAddressEligibility"

      parameters:
        - in: "body"
          name: "body"
          description: "Customer Address need to be verified"
          required: true
          schema:
            $ref: "#/definitions/Request"
      responses:
        "200":
          description: "Customer address is verified and valid customer."
          schema:
            $ref: "#/definitions/200Response"

        "404":
          description: "Invalid input/ Customer id should be the input."
          schema:
            $ref: "#/definitions/404Response"
  /healthCheck:
    get:
      tags:
        - "healthCheck"
      summary: "Verify the Health"
      description: "Check the Health"
      operationId: "getHealthCheck"
      responses:
        "200":
          description: "CReturn Health Status"
          schema:
            $ref: "#/definitions/200HealthCheckResponse"
definitions:
  Request:
    type: "object"
    properties:
      id:
        type: "integer"
        example: 2423

  200Response:
    type: "object"
    properties:
      data:
        type: "object"
        properties:
          isEligible:
            type: "boolean"
          reason:
            type: "string"
  200HealthCheckResponse:
    type: "object"
    properties:
      status:
        type: "string"
        example: "Success"

  404Response:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
